##### Basado en el libro Python for Data Analysis (Wes McKinney).

# NumPy: Arreglos eficientes


Numpy (Numerical Python) es la librería fundamental de Python para realizar análisis de datos, ya que es la base sobre la cual están construidas gran parte de las otras librerías especializadas que se utilizan. Numpy provee:

- ndarray: arreglo multidimensional rápido y eficiente para operaciones numéricas. Una matriz en numpy es un arreglo de 2 dimensiones (filas y columnas). tener en cuenta que los arreglos pueden tener N-dimensiones: por ejemplo, un video puede tener coordenadas x,y de un bojeto y además una tercera dimensión del tiempo.
Un arreglo es una estructura de datos (forma de organizar los datos) con elementos homogéneos (del mismo tipo) y ordenados reconocidos por un nombre en común. 

- Permite hacer operaciones en todos los elementos sin necesidad de loops.

- Lectura y guardado de los arreglos en disco

- Sirve para álgebra lineal, generación de números aleatorios, etc.

- Permite integración con código escrito en C, C++, Fortran. Esto ha permitido muchas veces usar Python como lenguaje para migrar código de C o Fortran a una interfaz más fácil de usar como la de python.

A pesar de que muchas veces no se usará numpy directamente, conocer como funcionan los numpy arrays permitirá entender mejor qué ocurre por debajo en otras librerías (ej: pandas).

Nos enfocaremos en las siguientes funcionalidades de numpy:

- Operaciones rápidas en arreglos para limpieza, submuestreo, filtrado y transformación de datos

- Ordenamiento, indexación y operaciones entre conjuntos

- Estadística descriptiva 

- Manipulación de datos para combinar conjuntos de datos heterogéneos

- Lógica condicional usando expresiones con arreglos en vez de con loops

A pesar de que Numpy provee todas estas operaciones, es más común y sencillo usarlas con una librería como pandas, ya que provee una interfaz más amigable al usuario y fácil de explorar, además de agregar otras funcionalidades como por ejemplo el manejo de series temporales.


In [1]:
## Importar numpy y definir configuraciones generales
import numpy as np
np.random.seed(12345) # Fijar semilla para la reproducilibidad
np.set_printoptions(precision=4, suppress=True) # 4 decimales de precision

In [2]:
# Version de numpy usada en el computador donde se creo el notebook
# (Si usan una version diferente pueden que vean muy leves diferencias en los resultados, pero en 
# general todos los resultados deben ser equivalentes)
np.__version__

'1.23.4'

Esta comparación muestra que efectivamente aplicar operaciones en un arreglo de numpy es mucho más rápido que hacerlas en listas elemento a elemento:

In [3]:
my_arr = np.arange(10000000)
my_list = list(range(10000000))

In [4]:
# Tiempo para multiplicar todos los elementos por 2 usando listas de Python
%time for i in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 12 s


In [5]:
# Tiempo para multiplicar todos los elementos por 2 usando un arreglo (array) de Numpy
%time for i in range(10): my_arr2 = my_arr * 2


Wall time: 201 ms


## El NumPy ndarray: un arreglo multidimensional

La principal característica de Numpy es su arreglo N-dimensional (ndarray), el cual es un contenedor rápido y flexible para almacenar grandes conjuntos de datos y permitir la aplicación de operaciones matemáticas en estos:





In [6]:
#Crear numpy array de 2 dimensiones con datos aleatorios (al ser 2d es una matriz)
data = np.random.randn(2, 3)
data

array([[-0.2047,  0.4789, -0.5194],
       [-0.5557,  1.9658,  1.3934]])

In [7]:
### Puedo aplicar facilmente operaciones matemticas 
data * 10


array([[-2.0471,  4.7894, -5.1944],
       [-5.5573, 19.6578, 13.9341]])

In [8]:
data + data

array([[-0.4094,  0.9579, -1.0389],
       [-1.1115,  3.9316,  2.7868]])

Todos los elementos del arreglo deben ser del mismo tipo. El arreglo tendrá una forma (shape) que indica el tamaño de cada dimensión, además de un tipo que indica los elementos que almacena:

In [9]:
data.shape


(2, 3)

In [10]:
data.dtype

dtype('float64')

### Crear ndarrays

Para crear un arreglo se usa la clase "array" de numpy. Esto recibe una secuencia y produce un numpy array:


In [11]:

data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1)
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [12]:
data1

[6, 7.5, 8, 0, 1]

Una lista de listas seria convertida a un arreglo multidimensional:

In [13]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [14]:
arr2.ndim

2

In [15]:
arr2.shape

(2, 4)

In [16]:
arr1.dtype

dtype('float64')

In [17]:
arr2.dtype

dtype('int32')

Existen otras funciones para crear arreglos. Es común por ejemplo crear arreglos de unos o ceros para ciertas operaciones de álgebra lineal (ej: valores propios).  Para estas creaciones, se pasa una tupla con las dimensiones:

In [18]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
np.ones((3, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### Ejercicio: 

Investigue como puede usar numpy para crear un arreglo que tenga los números de 3 a 300 contando de 3 en 3 (3,6,9,12...). 

Pista: busque el equivalente de range en numpy.

### Tipos de datos en ndarrays

Es posible definir el dtype al numpy array si no se quiere que numpy lo infiera de forma automática:

In [21]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [22]:
arr1.dtype ### El tipo float64 es el mas comun: un numero con punto flotante que ocupa 64 bits u 8 bytes

dtype('float64')

In [23]:
arr1

array([1., 2., 3.])

In [24]:
arr2.dtype

dtype('int32')

In [25]:
arr2

array([1, 2, 3])

Es posible convertir un arreglo de un tipo a otro:

In [26]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int32')

In [27]:
arr

array([1, 2, 3, 4, 5])

In [28]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [29]:
float_arr

array([1., 2., 3., 4., 5.])

In [30]:
### Strings a numericos
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings.astype(float) ### Numpy sabe que esto es np.float64

array([ 1.25, -9.6 , 42.  ])

### Aritmética con Numpy

Los arreglos permiten aplicar operaciones aritméticas sin necesidad de loops. Las operaciones aritméticas entre arreglos de igual tamaño se aplican elemento a elemento.



In [31]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [32]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [33]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [34]:
1 / arr

array([[1.    , 0.5   , 0.3333],
       [0.25  , 0.2   , 0.1667]])

In [35]:
arr ** 0.5

array([[1.    , 1.4142, 1.7321],
       [2.    , 2.2361, 2.4495]])

Incluso comparaciones booleanas elemento a elemento:

In [36]:
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [37]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [38]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [39]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

### Indexación y Slicing

Similar a las listas, hay varias formas de elegir partes de un arreglo:

In [40]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
arr[5] # indexacion

5

In [42]:
arr[5:8] #slicing

array([5, 6, 7])

In [43]:
arr[5:8] = 12 # asignacion con slicing
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

Puedo hacer indexación y slicing a objetos de varias dimensiones en cualquiera de las dimensiones.

In [44]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [45]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [47]:
arr2d[1, :2]

array([4, 5])

In [48]:
arr2d[:2, 2]

array([3, 6])

In [49]:
arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [50]:
arr2d[:2, 1:] = 0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [51]:
arr2d[-1, -1]

9

#### Ejercicio

Del arreglo arr3d, usando slicing, extraiga un subarreglo que contenga el 7, 8, 10 y 11.

In [52]:
arr3d = np.array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [53]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

##### Nota para aplicaciones futuras: 
Se debe tener en cuenta que en numpy, al hacer slicing o indexación de un arreglo, se está creando una referencia en vez de una copia. Esto en este momento no es tan relevante, pero a futuro se debe tener en cuenta (si alguna vez les pasa que al modificar un pedacito del arreglo se les esta modificando también el original, esta es la razón). https://numpy.org/doc/stable/user/basics.copies.html

### Filtrado usando Selección Booleana

Es muy común usar filtros para seleccionar de forma condicional algunos elementos de un arreglo. Para esto se usan booleanos para realizar la selección.

Supongamos que tenemos el siguiente arreglo de nombres con duplicados:

In [54]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [55]:
data

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

    
Suponer que cada nombre corresponde a una fila del arreglo data y que queremos seleccionar todas las filas con el nombre 'Bob'. Usamos el operador de comparación con el arreglo:

In [56]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

Y retornamos todas las filas donde la condición sea True:

In [57]:
data[names == 'Bob']

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.669 , -0.4386, -0.5397,  0.477 ]])

Esto se puede hacer también con negaciones:

In [58]:
names != 'Bob' ### Donde el nombre es diferente de bob

array([False,  True,  True, False,  True,  True,  True])

In [59]:
data[(names != 'Bob')]

array([[ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

Puedo elegir también varios nombres a incluir en mi condición:

In [60]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [61]:
names == 'Will'

array([False, False,  True, False,  True, False, False])

In [62]:
### Buscar donde el nombre sea Bob o Will
mask = (names == 'Bob') | (names == 'Will') ## No se puede usar "or", sino que se debe usar |
mask

array([ True, False,  True,  True,  True, False, False])

In [63]:
data[mask]

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241]])

Por ejemplo, una tarea común de limpieza de datos es cambiar todos los negativos por 0, y se usa un indice condicional sobre el arreglo (esto es muy usado para tareas de limpieza):

In [64]:
data

array([[ 0.0929,  0.2817,  0.769 ,  1.2464],
       [ 1.0072, -1.2962,  0.275 ,  0.2289],
       [ 1.3529,  0.8864, -2.0016, -0.3718],
       [ 1.669 , -0.4386, -0.5397,  0.477 ],
       [ 3.2489, -1.0212, -0.5771,  0.1241],
       [ 0.3026,  0.5238,  0.0009,  1.3438],
       [-0.7135, -0.8312, -2.3702, -1.8608]])

In [65]:
data < 0

array([[False, False, False, False],
       [False,  True, False, False],
       [False, False,  True,  True],
       [False,  True,  True, False],
       [False,  True,  True, False],
       [False, False, False, False],
       [ True,  True,  True,  True]])

In [66]:
data[data < 0] = 0 ### Donde data sea negativo, ponerlo en 0
data

array([[0.0929, 0.2817, 0.769 , 1.2464],
       [1.0072, 0.    , 0.275 , 0.2289],
       [1.3529, 0.8864, 0.    , 0.    ],
       [1.669 , 0.    , 0.    , 0.477 ],
       [3.2489, 0.    , 0.    , 0.1241],
       [0.3026, 0.5238, 0.0009, 1.3438],
       [0.    , 0.    , 0.    , 0.    ]])

Nota: usar selección boolean genera copias de los arreglos, en lugar de referencias al original.





### Trasponer y cambiar forma

Una operación común es transponer para cambiar filas por columnas o cambiar la forma del arreglo:

In [67]:
arr = np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [68]:
arr=arr.reshape((3, 5)) # cambiar la forma

In [69]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [70]:
arr.T # trasponerlo

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

### Lógica condicional con np.where

Esto es muy común en análisis de datos. Por ejemplo, supongamos que se quieren cambiar todos los números positivos por 1 y negativos por 0:

In [71]:
arr = np.random.randn(4, 4)
arr

array([[-0.8608,  0.5601, -1.2659,  0.1198],
       [-1.0635,  0.3329, -2.3594, -0.1995],
       [-1.542 , -0.9707, -1.307 ,  0.2863],
       [ 0.378 , -0.7539,  0.3313,  1.3497]])

Para lograr este objetivo, podemos usar np.where, con el arreglo de numpy que creamos, la condición que queremos (if), y que hacer si se cumple (then) y si no se cumple (else):

In [72]:
np.where(arr > 0, 1, 0) # Las posiciones donde sea positivo, ponga 1, en las demas, ponga 0

array([[0, 1, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 0, 1],
       [1, 0, 1, 1]])

Si quisiera simplemente saber en que posiciones se cumple y en cuales no la condición, podría hacer simplemente esto:

In [73]:
(arr > 0)

array([[False,  True, False,  True],
       [False,  True, False, False],
       [False, False, False,  True],
       [ True, False,  True,  True]])

### Métodos matemáticos y estadísticos

Numpy contiene también muchas operaciones matemáticas que pueden aplicarse sobre el arreglo: media, mediana, suma, etc:

In [74]:
arr = np.random.randn(5, 4)
arr

array([[ 0.0699,  0.2467, -0.0119,  1.0048],
       [ 1.3272, -0.9193, -1.5491,  0.0222],
       [ 0.7584, -0.6605,  0.8626, -0.01  ],
       [ 0.05  ,  0.6702,  0.853 , -0.9559],
       [-0.0235, -2.3042, -0.6525, -1.2183]])

In [75]:
arr.mean()

-0.12201389423276714

In [76]:
np.mean(arr)

-0.12201389423276714

In [77]:
arr.sum()

-2.440277884655343

Las puedo calcular también a nivel de filas o de columnas:

In [78]:
arr.mean(axis=1) ### Promedio de cada fila

array([ 0.3274, -0.2797,  0.2376,  0.1543, -1.0496])

In [79]:
arr.max(axis=0)  ## maximo de cada columna

array([1.3272, 0.6702, 0.8626, 1.0048])

### Ordenamiento

Al igual que las listas, podemos usar sort para ordenar un arreglo. El sort se hace inplace:

In [80]:
arr = np.random.randn(6)
arr

array([-1.3326,  1.0746,  0.7236,  0.69  ,  1.0015, -0.5031])

In [81]:
arr.sort()
arr

array([-1.3326, -0.5031,  0.69  ,  0.7236,  1.0015,  1.0746])

In [82]:
arr[::-1] # este es un truco que se hace para ponerlo en el orden contrario

array([ 1.0746,  1.0015,  0.7236,  0.69  , -0.5031, -1.3326])

Para arreglos multidimensionales, puedo especificar sobre que dimensión se ordenará:

In [83]:
arr = np.random.randn(5, 3)
arr

array([[-0.6223, -0.9212, -0.7262],
       [ 0.2229,  0.0513, -1.1577],
       [ 0.8167,  0.4336,  1.0107],
       [ 1.8249, -0.9975,  0.8506],
       [-0.1316,  0.9124,  0.1882]])

In [84]:
arr.sort(1) ## sobre las filas es 1, sobre las columnas es 0
arr

array([[-0.9212, -0.7262, -0.6223],
       [-1.1577,  0.0513,  0.2229],
       [ 0.4336,  0.8167,  1.0107],
       [-0.9975,  0.8506,  1.8249],
       [-0.1316,  0.1882,  0.9124]])

### Unicidad

El método unique retorna los valores únicos de un arreglo (los retorna ordenados):

In [85]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
np.unique(names)

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [86]:
ints = np.array([3, 3, 3, 2, 2, 1, 1, 4, 4])
np.unique(ints)

array([1, 2, 3, 4])

## Álgebra lineal



Numpy permite hacer varias operaciones de álgebra lineal: multiplicación matricial, descomposiciones, determinantes, etc. Multiplicar en Numpy con * es elemento a elemento; si se quiere multiplicación matricial, usar np.dot:

In [87]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x

array([[1., 2., 3.],
       [4., 5., 6.]])

In [88]:
y

array([[ 6., 23.],
       [-1.,  7.],
       [ 8.,  9.]])

In [89]:
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [90]:
np.dot(x, y)

array([[ 28.,  64.],
       [ 67., 181.]])

In [91]:
### Se puede usar también @
x@y

array([[ 28.,  64.],
       [ 67., 181.]])

In [92]:
np.dot(x, np.ones(3))

array([ 6., 15.])

Numpy.linalg tiene varias operaciones también muy comunes en álgebra lineal (como por ejemplo la inversa y la traspuesta). En el siguiente ejercicio, calculamos $(X^TX)^{-1}$. Esta operación es muy común en álgebra matricial y se usa para la solución de la regresión lineal múltiple por mínimos cuadrados ordinarios. (Se calcula la transpuesta de la matriz X, se multiplica por X y se invierte la matriz resultado).

In [93]:
from numpy.linalg import inv
X = np.random.randn(5, 5)
Xt = X.T
resultado_mult = Xt.dot(X)
resultado_final = inv(resultado_mult)
resultado_final



array([[ 2.8309, -5.8904, -3.7251,  1.0739,  1.6123],
       [-5.8904, 13.2978,  8.2231, -2.584 , -3.6936],
       [-3.7251,  8.2231,  5.2674, -1.6356, -2.3577],
       [ 1.0739, -2.584 , -1.6356,  0.8224,  0.808 ],
       [ 1.6123, -3.6936, -2.3577,  0.808 ,  1.3653]])

In [94]:
# en una linea
inv(X.T.dot(X))


array([[ 2.8309, -5.8904, -3.7251,  1.0739,  1.6123],
       [-5.8904, 13.2978,  8.2231, -2.584 , -3.6936],
       [-3.7251,  8.2231,  5.2674, -1.6356, -2.3577],
       [ 1.0739, -2.584 , -1.6356,  0.8224,  0.808 ],
       [ 1.6123, -3.6936, -2.3577,  0.808 ,  1.3653]])

### Ejercicios para clase:
https://libguides.ntu.edu.sg/python/numpyexercises




#### Algunos ejercicios sugeridos para estudiar en casa:

https://libguides.ntu.edu.sg/ld.php?content_id=48284525 (solo los ejercicios de nivel 1 y 2)

https://favtutor.com/blogs/numpy-exercises-python 

### Ejemplo de tutorial en numpy (opcional, no incluido en temas a evaluar)

Es común en la cotidianidad del trabajo en analítica tener que investigar en la web para buscar tutoriales que enseñen como usar las librerías de Python para un determinado fin.

Por ejemplo, supongamos que necesitamos manipular imagenes usando numpy. Y buscamos en google "numpy processing images". Y decidimos seguir el tutorial de analytics vidha para aprender:

https://www.analyticsvidhya.com/blog/2021/05/image-processing-using-numpy-with-practical-implementation-and-code/#h2_5

Guarden la imagen como jpg desde la página web (usar la herramienta recortes) y sigan el tutorial.

Llegar hasta la parte de "Blending Images".